### ISSUE TITLE
[UNKNOWN BUG] AUR

### ISSUE THREAD

**Issue by OtakuLinux** [HackerPolice/MissedIT-csgo#2]
Package from AUR not founded (error 404)

**Comment by tutoraddicts** [comment]
Which Linux distro you are using???

**Comment by OtakuLinux** [comment]
> Which Linux distro you are using???
Manjaro, this error I seen in internet browser

**Comment by tutoraddicts** [comment]
You get this error because some packages are not installed that the software need .... you just need install that package

**Comment by ShayBox** [comment]
No, you get this error because the aur package was taken down because it's a cheat, packages like that aren't allowed on the arch user repository.

**Comment by OtakuLinux** [comment]
Then why is Fuzion in AUR?

**Comment by tutoraddicts** [comment]
> Then why is Fuzion in AUR?

Did not get you man

**Comment by OtakuLinux** [comment]
[https://aur.archlinux.org/packages/fuzion-git/](url) - Fuzion, [https://github.com/LWSS/Fuzion](url)
